-- Create admin user with username 'admin' and password 'password'
-- This script generates the BCrypt hash and inserts the admin user

USE auth_db;

-- Delete existing admin user if it exists
DELETE FROM users_auth WHERE username = 'admin';

-- Insert admin user with BCrypt hash for password 'password'
-- Hash generated using: mvn compile exec:java -Dexec.mainClass="edu.univ.erp.util.HashPassword" -Dexec.args="password"
-- You should generate a fresh hash and replace this placeholder
INSERT INTO users_auth (user_id, username, role, password_hash, status) VALUES
(1, 'admin', 'admin', '$2a$12$HwzuOJ/4JxN1HawTBg5OAuv5ekvA6Upm.Izt0Sa9De7vOj03me8Ie', 'active');

-- Note: Replace <BCRYPT-HASH-FOR-PASSWORD> with the actual hash generated by HashPassword.java
-- Run: mvn compile exec:java "-Dexec.mainClass=edu.univ.erp.util.HashPassword" "-Dexec.args=password"



